### ISSUE TITLE
computational bottlenecks

### ISSUE THREAD

**Issue by mcieslik-mctp** [arshajii/ema#2]
I have run the EMA workflow with great results. Even beyond the smart aligner I really like that you provided third-party implementations to critical steps in 10x data analysis i.e. barcode correction and barcode-aware duplicate marking.  While the software certainly works well in it's current state, I wonder whether you would consider addressing some of the most critical computational bottlenecks.

1. The FASTQ preprocessing step is currently a single-threaded bottleneck in the pipeline execution taking ~50% of the overall wall-clock run-time on our hardware.
2. Parallelization of the sorting / alignment / duplicate marking steps requires at least 8GB of memory per-core, making it impractical on 64+ core servers.
3. Use of Picard.

I think 1. could be possibly alleviated using the following strategy.
```
fastq.gz -> gunzip | split -l 40e6 > chunked_fastq
chunked_fastq > fix_barcode > barcoded_chunked_fastq
barcoded_fastq(s) >  split_by_barcode > buckets
```
The first and last step's would remain single-threaded, but at least barcode fixing would be parallelized. 
For 3. I would suggest using sambamba to mark the duplicates, the software is multi-threaded so using it with ~4 cores per bucket (and process fewer buckets in parallel) would lower memory requirements.

Thanks!

**Comment by inumanag** [comment]
Thanks for the suggestion! This has been implemented internally, and we will release it by the end of this week.

**Comment by arshajii** [comment]
Thanks for your patience. We just implemented the following:

1. Faster (multithreaded) preprocessing
2. Multithreading within EMA, using only a single copy of the data structures needed for alignment
3. Duplicate marking within EMA, and duplicate marking for BWA with sambamba

More details are in the new README. I'll close this issue for now, but please let us know if you run into any issues, or have any more questions/suggestions!

**Comment by mcieslik-mctp** [comment]
Thank you for your efforts, I will try-out the new version and report back.

**Comment by inumanag** [comment]
Here are some numbers in case you are interested: on NA12878 dataset (64GB gzipped), pre-processing takes 27 minutes on 40 cores for gzipped sample (2 mins for counting and 25 mins for correcting). If you want H2 correction (as in paper), add extra 15 minutes to the correction step (although impact of it is negligible, but if you want 100% compatibility with Long Ranger fo with this). In total, it should take less than 1hr (even with 20 threads w/o H2, since most of the time is spent on I/O). Afterwards, we also trimmed down the times by plugging in sorting and duplicate marking directly in EMA. All in total, it takes ~10hrs on 40 cores from the initial fastq.gz files to the final indexed, marked and sorted BAM.

Best,
