### ISSUE TITLE
10X Long Ranger with EMA BAM

### ISSUE THREAD

**Issue by wjalvarez** [arshajii/ema#26]
Hello,

We have barcoded short-read samples that we aligned with EMA and we are interested in using the resulting BAM file for the 10x Long Ranger pipeline. Specifically, we would like to provide the EMA BAM file as input for Long Ranger's structural variant calling and other downstream analyses. For single variants we already used GATK's HaplotypeCaller (v4.0.8.1) on the BAM file as described in your experimental pipeline. It seems that this pipeline only accepts fastq files for input and we would like to know if it would be possible to instead use results from EMA.

**Comment by inumanag** [comment]
Hi @wjalvarez :

We have already tried to integrate EMA with Long Ranger before but it turned out to be futile exercise as Long Ranger is (1) not documented and (2) relies way too much on internal flags and files that would take way too much to reverse engineer on our side (it's not as simple as BAM replacement, sadly). 

Maybe we should ask Long Ranger developers to support BAM input.
